defaults:
  - finetune
  - /hydra/sweeper: CIR  # Load CIR-specific sweep params (used with --multirun)

handler: CIR
args:
  optim: sgd  # adam underperforms
  learning_rate: 0.4
  lr_scheduler_type: constant
  gradient_accumulation_steps: 1  # must be one, because CIR modifies gradients in-place

method_args:
  cfg:
    n_pcs: 200

    retain_momentum: 0.9

    train_first_layers: 0.75

    lora_rank: 8
    lora_alpha: 16
    adv_lr: 0.001
    adv_decay: 0.99