defaults:
  - finetune

handler: RepSelect
args:
  optim: sgd  # adam underperforms
  learning_rate: 0.2
  lr_scheduler_type: constant
  gradient_accumulation_steps: 1  # must be one, because RepSelect modifies gradients in-place

method_args:
  cfg:
    n_pcs: 400
    retain_momentum: 0.97
    lora_lr: 0.1
    lora_rank: 32
    use_distribution: forget  # forget | retain
    kl_mask: module  # module | disrproj