defaults:
  - finetune

handler: RepSelectSimple
args:
  learning_rate: 0.05

method_args:
  n_pcs: 500
  lora_lr: 0.01
  act_collapse: forget  # forget | retain | none
  grad_collapse: forget  # forget | retain | none
  # distribution: forget  # forget | retain
  # collapse_on: both  # act | grad | both | none
  use_lora: true
