defaults:
  - finetune

handler: RetainAwareCollapse
args:
  optim: sgd
  learning_rate: 0.2
  lr_scheduler_type: constant
  gradient_accumulation_steps: 1

method_args:
  cfg:
    n_pcs: 400
    retain_momentum: 0.97
    lora_lr: 0.1
    lora_rank: 32
    reg_eps: 1e-4
