# @package hydra.sweeper
params:
  trainer.args.learning_rate: "tag(log, interval(0.3, 30))"
  trainer.method_args.lora_lr: "tag(log, interval(0.3, 30))"
  trainer.method_args.n_pcs: "tag(log, range(400, 600))"