model_args:
  # pretrained_model_name_or_path: "google/gemma-4-E4B"
  pretrained_model_name_or_path: "filypo/gemma-4-E4B-text-only"
  # attn_implementation: 'flash_attention_2'  # causes error, that head dimension is too high
  torch_dtype: bfloat16
tokenizer_args:
  # pretrained_model_name_or_path: "google/gemma-4-E4B"
  pretrained_model_name_or_path: "filypo/gemma-4-E4B-text-only"
template_args:
  apply_chat_template: False
model_handler: Gemma4ForCausalLM  # text-only version