model_args:
  pretrained_model_name_or_path: "Qwen/Qwen2.5-3B"
  attn_implementation: 'flash_attention_2'
  torch_dtype: bfloat16
tokenizer_args:
  pretrained_model_name_or_path: "Qwen/Qwen2.5-3B"
template_args:
  apply_chat_template: false